# image will be published to ghcr.io/<user>/<name>
name: mj-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
    ## Install MS RPM repo
  # - type: script
  #   snippets:
  #     - "curl -sSL -O https://packages.microsoft.com/config/<distribution>/<version>/packages-microsoft-prod.rpm > /tmp/packages-microsoft-prod.rpm"
  #     - "rpm -i /tmp/packages-microsoft-prod.rpm"
  #     - "rm /tmp/packages-microsoft-prod.rpm"
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/varlad/zellij/repo/fedora-%OS_VERSION%/varlad-zellij-fedora-%OS_VERSION%.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      - https://packages.microsoft.com/config/fedora/40/prod.repo # hardcoded 40!
      - https://packages.microsoft.com/yumrepos/edge/config.repo
      - https://packages.microsoft.com/yumrepos/vscode/config.repo
    install:
      - fish
      - zellij
      - chromium
      - tailscale
      - podman-docker
      - docker-compose
      - microsoft-edge-stable
      - code
      
  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        # - org.mozilla.firefox
        # - org.gnome.Loupe
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
      # - org.gnome.eog

  - type: systemd
    system:
      enabled:
      - tailscaled

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

