# image will be published to ghcr.io/<user>/<name>
name: mj-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
    ## Install MS RPM repo
  # - type: script
  #   snippets:
  #     - "curl -sSL -O https://packages.microsoft.com/config/<distribution>/<version>/packages-microsoft-prod.rpm > /tmp/packages-microsoft-prod.rpm"
  #     - "rpm -i /tmp/packages-microsoft-prod.rpm"
  #     - "rm /tmp/packages-microsoft-prod.rpm"
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/varlad/zellij/repo/fedora-%OS_VERSION%/varlad-zellij-fedora-%OS_VERSION%.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      - https://packages.microsoft.com/config/fedora/40/prod.repo # hardcoded 40!
      - https://packages.microsoft.com/yumrepos/edge/config.repo
      - https://downloads.k8slens.dev/rpm/lens.repo
    install:
      - fish
      - zellij
      - chromium
      - tailscale
      - podman-docker
      - docker-compose
      - microsoft-edge-stable
      - https://github.com/mockoon/mockoon/releases/download/v8.1.1/mockoon-8.1.1.x86_64.rpm
      - https://code.visualstudio.com/sha/download?build=stable&os=linux-rpm-x64
      - lens
      
  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      install:
        - app.drey.Dialect
        - ca.desrt.dconf-editor
        - com.belmoussaoui.Obfuscate
        - com.getpostman.Postman
        - com.github.finefindus.eyedropper
        - com.github.jeromerobert.pdfarranger
        - com.github.liferooter.textpieces
        - com.github.maoschanz.drawing
        - com.github.marhkb.Pods
        - com.github.tchx84.Flatseal
        - com.github.tenderowl.frog
        - com.mattjakeman.ExtensionManager
        - com.mongodb.Compass
        - com.rafaelmardojai.Blanket
        - com.raggesilver.BlackBox
        - com.simplenote.Simplenote
        - dev.deedles.Trayscale
        - dev.skynomads.Seabird
        - io.dbeaver.DBeaverCommunity
        - io.github.fabrialberio.pinapp
        - io.gitlab.adhami3310.Converter
        - io.gitlab.adhami3310.Impression
        - io.missioncenter.MissionCenter
        - net.nokyan.Resources
        - org.gnome.Builder
        - org.gnome.Epiphany
        - org.gnome.Loupe
        - org.gnome.design.IconLibrary
        - org.gnome.meld
        - org.kde.ark
        - org.localsend.localsend_app
        - org.nickvision.tubeconverter
        - org.onlyoffice.desktopeditors
        - page.codeberg.libre_menu_editor.LibreMenuEditor
        - re.sonny.Playhouse

  - type: systemd
    system:
      enabled:
      - tailscaled

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

